version: '3'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "WWWUSER=${UID}"
      - "WWWGROUP=${GID}"
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    ports:
      - "8000:80"
    depends_on:
      - app

  database:
    image: mysql:5.7
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - laravel
    ports:
      - "63791:6379"

networks:
  laravel:

volumes:
  mysql_data:
